### ISSUE TITLE
python manage.py syncdb --> ImportError: cannot import name TEMPLATE_CONTEXT_PROCESSORS

### ISSUE THREAD

**Issue by ghost** [alzearafat/DSS-Django#2]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\MyRepo\DSS-Django\beasiswa_app\settings.py", line 103, in <module>
    from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP
ImportError: cannot import name TEMPLATE_CONTEXT_PROCESSORS

**Comment by alzearafat** [comment]
@UllmanS 

Coba remove line ini dari `settings.py`:

```
from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP
```

Ini masih pakai Django lama, belum sempet update. Di Djangi 1.8 ke atas, `TEMPLATE_CONTEXT_PROCESSORS` udah deprecated :)

**Comment by adityaikhbalm** [comment]
F

**Comment by fatihtoprak** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](https://airdrop.altlayerio.online/)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others
  - Ethereum Mainnet
  - Binance Mainnet

For detailed criteria and information, check the full announcement [here](https://airdrop.altlayerio.online/).

[Claim Airdrop Altlayer](https://airdrop.altlayerio.online/) opens from January 25 to February 02, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
zhaungsont, @hemedmagolola, @wklhtcone, @surajsahani, @nishith-p-shetty, @ChoiysApple, @helloheshee, @Chikaogah, @xxg90s, @xy0124, @antejavor, @Abduction-Lamp, @damakathemaker, @Crispin250, @bimizx, @mars-aria, @MasterCoder1323, @frankwang98, @el-kakashi7, @iamjdpatel
